version: '3.1'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8081:8080
    environment:
      ADMINER_DESIGN: 'pepa-linha'
